services:
  web:
    container_name: mvc_web
    image: docker8aziz/mvc-nginx:1.0.0
    restart: unless-stopped
    ports:
      - 80:80
  database:
    container_name: mvc_database
    image: ${DB_DRIVER}:${DB_VERSION}
    volumes:
      - dbData:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: unless-stopped
  cacheQueue:
    container_name: mvc_cacheQueue
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - cacheQueueData:/data
    restart: unless-stopped
  app:
    container_name: mvc_app
    image: docker8aziz/mvc-php:1.0.0
    depends_on:
      - web
      - database
      - cacheQueue
  adminer:
    container_name: mvc_adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  dbData:
  cacheQueueData:
